app:
    resource: "@AppBundle/Controller/"
    type:     annotation

user_new:
  path: /new
  defaults: { _controller: AppBundle:User:new }

user_create:
  path: /user_create
  defaults: { _controller: AppBundle:User:create }

