<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RandPlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RandPlRepository extends EntityRepository
{
    public function isAnything()
    {
        $qb = $this->createQueryBuilder('d');

        return $qb
              ->select(array('d.id', 'd.randPlWord'))
              ->where('d.id = :id')
              ->setParameter('id', 1)
              ->getQuery();
    }

    public function updateRandomPl($random)
    {
        $qb = $this->createQueryBuilder('u');

        return $qb
              ->update('AppBundle:RandPl')
              ->set('u.randPlWord', $qb->expr()->literal($random))
              ->where('u.id = :id')
              ->setParameter('id', 1)
              ->getQuery();
    }
}
