<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\ArrayCollection;
//use AppBundle\Controller\LearningController;

/**
 * WordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordRepository extends EntityRepository
{

    public function count()
    {

         $qb = $this->createQueryBuilder('t');
         return $qb
               ->select('count(t.id)')
               ->getQuery()
               ->getSingleScalarResult();
    }


    public function pullTheWord($random)
    {
        $qb = $this->createQueryBuilder('d');
        return $qb
            ->select(array('d.plWord'))
            ->where('d.id = :id')
            ->setParameter('id', $random)
            ->orderBy('d.plWord')
            ->getQuery();

    }

    public function takeOut($engWord)
    {
        $qb = $this->createQueryBuilder('w');

        return $qb
              ->select(array('w.id', 'w.engWord'))
              ->where('w.engWord = :engWord')
              ->setParameter('engWord', $engWord)
              ->getQuery();
    }

    public function supportEng($random)
    {
        $qb = $this->createQueryBuilder('w');
        
        return $qb
              ->select(array('w.id', 'w.engWord'))
              ->where('w.id = :id') 
              ->setParameter('id', $random)
              ->getQuery(); 
    }

}
